format_version: 10
pipelines:
  vault:
    group: Tools
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-a66247d:
        git: https://github.com/raghudevopsb79/tools-automation
        shallow_clone: true
        auto_update: true
        branch: main
    secure_variables:
      SSH_PASSWORD: "AES:GJpOsKchZolqf2Gylrqymw==:48C77QmHmE7ihFUNFmoXRw=="
    environment_variables:
      tool_name: vault
    stages:
    - DEV:
        fetch_materials: true
        approval:
          type: manual
        jobs:
          ansible:
            timeout: 0
            tasks:
            - exec:
                command: bash
                arguments:
                - setup-tool-service.sh
